RocketLauncher/Controllers/TenantController.cs
using DataTransferObject;
using DataTransferObject.DTO;
using DataTransferObject.Enums;
using Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Reflection;
namespace RocketLauncher.Controllers
{
    [Route("tenants")]
    public class TenantController : Controller
    {
        private readonly UserIService _userService;
        private readonly TenantIService _tenantService;
        public TenantController(UserIService userService, TenantIService tenantService)
        {
            _userService = userService;
            _tenantService = tenantService;
        }
        [Route("index")]
        public IActionResult Index()
        {
            List<TenantResponse> SorteduserList = _userService.ListAllTenantUsers();
            return View(SorteduserList);
        }
        [Route("create")]
        [HttpGet]
        public IActionResult CreateTenant()
        {
            //List<TenantResponse> tenants = _userService.ListAllTenantUsers();
            //ViewBag.Tenants = tenants;
            return View();
        }
        [HttpPost]
        [Route("create")]
        public IActionResult CreateUser(TenantAddRequest tenantAddRequest)
        {
            if (!ModelState.IsValid)
            {
                //List<TenantResponse> tenants = _userService.ListAllTenantUsers();
                //ViewBag.Tenants = tenants;
                ViewBag.Errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList();
                return View();
            }

            //call the service method
            TenantResponse userResponse = _userService.AddTenant(tenantAddRequest);

            //navigate to Index() action method (it makes another get request to "users/index"
            return RedirectToAction("Index", "User");
        }
        [HttpGet]
        [Route("update/{userID}")] //Eg: /persons/edit/1
        public IActionResult UpdateUser(Guid userId)
        {
            UserResponse? userResponse = _userService.GetUserByID(userId);
            if (userResponse == null)
            {
                return RedirectToAction("Index");
            }

            UserUpdateRequest userUpdateRequest = userResponse.toUserUpdateRequest();

            List<TenantResponse> tenants = _userService.ListAllTenantUsers();
            ViewBag.Tenants = tenants.Select(temp =>
            new SelectListItem() { Text = temp.TenantName, Value = temp.TenantID.ToString() });

            return View(userUpdateRequest);
        }

        [HttpPost]
        [Route("update/{userID}")]
        public IActionResult UpdateUser(UserUpdateRequest userUpdateRequest)
        {
            UserResponse? userResponse = _userService.GetUserByID(userUpdateRequest.UserId);

            if (userResponse == null)
            {
                return RedirectToAction("Index");
            }

            if (ModelState.IsValid)
            {
                UserResponse updatedUser = _userService.UpdateUser(userUpdateRequest);
                return RedirectToAction("Index");
            }
            else
            {
                List<TenantResponse> tenants = _userService.ListAllTenantUsers();
                ViewBag.Tenants = tenants.Select(temp =>
                new SelectListItem() { Text = temp.TenantName, Value = temp.TenantID.ToString() });

                ViewBag.Errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList();
                return View(userUpdateRequest);
            }
        }
        [HttpGet]
        [Route("delete/{userID}")] //Eg: /persons/edit/1
        public IActionResult DeleteUser(Guid userId)
        {
            UserResponse? userResponse = _userService.GetUserByID(userId);
            return View(userResponse);
        }

        [HttpPost]
        [Route("delete/{userID}")]
        public IActionResult DeleteUser(UserUpdateRequest userUpdateRequest)
        {
            UserResponse? userResponse = _userService.GetUserByID(userUpdateRequest.UserId);
            _userService.DeleteUser(userUpdateRequest.UserId);
            return RedirectToAction("Index");

        }
    }
}

RocketLauncher/Views/Tenant/CreateTenant.cshtml
@{
    ViewBag.Title = "Create User";
}
<a href="~/users/index" class="link-hover"> Back to User List</a>
<h2>Create Tenant</h2>
<div class="w-50">
    <form action="~/tenants/create" method="post">
        @*TenantName*@
        <div class="form-field flex">
            <div class="w-25">
                <label for="TenantName" class="form-label">TenantName</label>
            </div>
            <div class="flex-1">
                <input type="text" id="TenantName" name="TenantName" class="form-input" />
            </div>
        </div>
        @*Slug*@
        <div class="form-field flex">
            <div class="w-25">
                <label for="Slug" class="form-label">Slug</label>
            </div>
            <div class="flex-1">
                <input type="text" id="Slug" name="Slug" class="form-input" />
            </div>
        </div>
        @*ContactEmail*@
        <div class="form-field flex">
            <div class="w-25">
                <label for="ContactEmail" class="form-label">ContactEmail</label>
            </div>
            <div class="flex-1">
                <input type="email" id="ContactEmail" name="ContactEmail" class="form-input" />
            </div>
        </div>
        @*AddressLine1*@
        <div class="form-field flex">
            <div class="w-25">
                <label for="AddressLine1" class="form-label pt">AddressLine1</label>
            </div>
            <div class="flex-1">
                <input type="text" id="AddressLine1" name="AddressLine1" class="form-input" />
            </div>
        </div>

        @*Submit*@
        <div class="form-field flex">
            <div class="w-25">
            </div>
            <div class="flex-1">
                <button class="button button-green-back">Create</button>

                @if (ViewBag.Errors != null)
                {
                    <div class="text-red ml">
                        <ul>
                            @foreach (string error in ViewBag.Errors)
                            {
                                <li class="ml">@error</li>
                            }
                        </ul>
                    </div>
                }
            </div>
        </div>
    </form>
</div>

RocketLauncher/Views/Tenant/Index.cshtml
@model IEnumerable<TenantResponse>


@{
    ViewBag.Title = "Tenant List";
}
<form action="~/tenants/index" method="get">
    <h1> Tenants </h1>
    <a href="~/tenants/create">Create Tenant</a>
<h1>Tenant List</h1>

<table class="table table-striped table-bordered w-100 mt-3">
        <thead>
            <tr>
                <th>
                        Tenant ID
                </th>
                <th>
                    <a asp-controller="Tenant"
                       asp-action="Index">
                        Tenant Name
                    </a>
                    <i class="fa-solid"></i>
                </th>
                <th>
                    <a asp-controller="Tenant"
                       asp-action="Index">
                        Address
                    </a>
                    <i class="fa-solid"></i>
                </th>
                <th>
                    <a asp-controller="Tenant"
                       asp-action="Index">
                        Slug
                    </a>
                    <i class="fa-solid"></i>
                </th>

                <th>
                    <a asp-controller="Tenant"
                       asp-action="Index">
                        IsActive
                    </a>
                    <i class="fa-solid"></i>
                </th>

                <th>
                    <a asp-controller="Tenant"
                       asp-action="Index">
                        Creation Time
                    </a>
                    <i class="fa-solid"></i>
                </th>

                <th>
                    <a asp-controller="Tenant"
                       asp-action="Index">
                        Contract Email
                    </a>
                    <i class="fa-solid"></i>
                </th>

            </tr>
        </thead>
    <tbody>
        @if (Model != null && Model.Any())
        {
            foreach (var user in Model)
            {
                <tr>
                    <td>@user.TenantID</td>
                    <td>@user.TenantName</td>
                    <td>@user.AddressLine1</td>
                    <td>@user.Slug</td>
                    <td>@user.IsActive</td>
                    <td>@user.CreatedAtUtc.ToString("yyyy-MM-dd")</td>
                    <td>@user.ContactEmail</td>
                    <td>
                            <a asp-controller="Tenant" asp-action="UpdateUser" asp-route-UserID="@user.TenantID">Edit</a>
                    </td>
                    <td>
                            <a asp-controller="Tenant" asp-action="DeleteUser" asp-route-UserID="@user.TenantID">Delete</a>
                   </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="10" class="text-center text-muted">
                    No users found.
                </td>
            </tr>
        }
    </tbody>
</table>
</form>